export const roomdata=[
    {
       'roomNumber':'202',
        'adultCapacity':'2',
        'childCapacity':'3',
        'price':'2000$'
    },
    {
        'roomNumber':'203',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     },
     {
        'roomNumber':'204',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     },
     {
        'roomNumber':'205',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     },
     {
        'roomNumber':'206',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     },
     {
        'roomNumber':'207',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     },
     {
        'roomNumber':'202',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     },
     {
        'roomNumber':'202',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     }, {
        'roomNumber':'202',
         'adultCapacity':'2',
         'childCapacity':'3',
         'price':'2000$'
     },


]